### ISSUE TITLE
There is no method to create the sdk_token.

### ISSUE THREAD

**Issue by mukeshkumar1986** [onfido/api-java-client#1]
There is no method in this API to create the [sdk_token](https://documentation.onfido.com/#sdk-tokens).

**Comment by stephencookdev** [comment]
Hey @mukeshkumar1986 - you shouldn't need the SDK token for this, just the API token.

This is explained a bit more [on our developer hub](https://developers.onfido.com/quick-start#authentication), and [on your Dashboard](https://onfido.com/dashboard/v2/#/api/tokens) if you wanted to read in a bit more detail

But basically, if you don't currently have an API (not SDK) token, then you'll need to raise a ticket with the Onfido support team to request one 🙂

**Comment by mukeshkumar1986** [comment]
That is correct I don't need SDK token for accessing the APIs. But for the Web SDK I need to create SDK token and need to make an API call which is not supported by this API.

**Comment by stephencookdev** [comment]
Hey @mukeshkumar1986 - would you mind starting an email thread api@onfido.com ? That'll be the best way to get the right person on the job to help you out!
